spring:
  security:
    user:
      name: admin
      password: 123456

  datasource:
    url: jdbc:postgresql://localhost:5433/taskdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: taskmanager

server:
  port: 8080